services:
  nsxlibrarymanager:
    container_name: nsxlibrarymanager
    # Use the published Docker Hub image by default. The build context is kept so
    # you can still build locally with `docker compose build` if needed.
    image: newolonos/nsxlibrarymanager:latest
    build:
      context: .
    volumes:
      - /mnt/nfs/library:/app/library
      - /srv/nsxlibrarymanager/icon:/app/wwwroot/images/icon
      - /srv/nsxlibrarymanager/config:/app/config
      - /srv/nsxlibrarymanager/data:/app/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '8080:8080'
    environment:
      - PUID=1000
      - PGID=1000
    restart: always