name: Build and Publish to Docker Hub

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

concurrency:
  group: docker-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            newolonos/nsxlibrarymanager:latest
            newolonos/nsxlibrarymanager:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Inspect pushed manifest
        run: |
          echo "Inspecting docker.io/newolonos/nsxlibrarymanager:latest"
          docker buildx imagetools inspect docker.io/newolonos/nsxlibrarymanager:latest || true
